name: Deploy site to Cloudflare Pages

on:
  push:
    # main is "production", test is "preview" in Cloudflare
    branches: ["main", "test"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Example
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prep Vars
        run: |
          git fetch --tags
          export TAG=$(git log --tags --max-count=1 --format="%(describe:abbrev=0)")
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Create and Publish GitHub Release
        uses: softprops/action-gh-release@v2.0.4
        id: create_release
        with:
          tag_name: v${{ env.VERSION }}
          name: Build v${{ env.VERSION }}
          body: |
              Build v$${{ env.VERSION }} created from ${{ github.ref }} @${{ github.sha }}
          prerelease: false

      - name: Publish to Cloudflare Pages
        id: publish
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 3100a6223762be291d2adab89520916f
          projectName: companion
          directory: public
          branch: ${{ github.ref_name}}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Outputs
        run: |
          echo "## Build ${{ env.VERSION }} Deployed to Cloudflare" >> $GITHUB_STEP_SUMMARY
          echo "ID: ${{ steps.publish.outputs.id }}" >> $GITHUB_STEP_SUMMARY
          echo "URL: ${{ steps.publish.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "Environment: ${{ steps.publish.outputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "Alias: ${{ steps.publish.outputs.alias }}" >> $GITHUB_STEP_SUMMARY
